config/routes.rb
Platform::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" } do
   get 'users/sign_out' => "devise/sessions#destroy"
   get 'users/sign_in' => "site#index"
  end

  get 'site/newsfeeds'
  
  get "admin" => "admin#index"

  mailboxes_for :users
  
  get "home" => "site#home"

  mount Ckeditor::Engine => '/ckeditor'

  post "search" => "search#index"

  resources :feedbacks

  namespace :admin do
    resources :forms
    get "members/index"
    post "members/edit"
    get "groups/index"
    post "groups/edit"
    get "activities/index"
    post "activities/edit"
    post "activities/change_group"
  end

  namespace :form do 
    resources :second_building_applications do 
      member do
        post :approve
        post :reject
      end
    end
  end

  resources :profiles do
    member do
      get 'like'
      get 'unlike'
      get 'users'
      put 'update_status'
    end
    collection do 
      get 'token'
    end
  end

  resources :groups do
    collection do
      get 'wall'
    end
    member do
      get 'join'
      get 'exit'
      get 'like'
      get 'unlike'
      get 'description'
      get 'history'
      get 'organization'
      get 'activities'
      get 'comments'
      get 'members'
      get 'sms' => 'sms#index'
      post 'sms/push' => 'sms#push'
      namespace :admin do
        get 'members'
        get 'forms'
        get 'introduction'
        get 'description'
        get 'history'
        get 'organization'
        post 'members' => 'groups#edit_members'
      end
      namespace :form do
        get 'second_building/new' => 'second_building_applications#new'
      end
    end
    resources :circles do
      collection do
        post 'change_boss/:user_id' => 'circles#change_boss'
        post 'update/:user_id' => 'circles#update_user'
        post 'approve/:user_id' => 'circles#approve'
        post 'reject/:user_id' => 'circles#reject'
        post 'kickout/:user_id' => 'circles#kickout'
      end
    end
    resources :activities, :only => [:new, :create]
  end

  resources :activities do
    collection do
      get 'tag_cloud'
      get 'wall'
    end
    member do
      get 'join'
      get 'exit'
      get 'unlike'
      get 'like'
    end
    resources :blogs 

    resources :pictures do
      member do
        get 'show_gallery'
        get 'load'
      end
    end
    resources :albums 
    resources :circles do
      collection do
        post 'update/:user_id' => 'circles#update_user'
        post 'change_boss/:user_id' => 'circles#change_boss'
        post 'approve/:user_id' => 'circles#approve'
        post 'reject/:user_id' => 'circles#reject'
        post 'kickout/:user_id' => 'circles#kickout'
      end
    end
  end

  resources :comments, :only => [:create, :destroy]

  get 'circles/:id/message' => 'circles#message', :as=>'message_circle'

  get 'tags' => 'application#tags'

  root :to => "site#index"

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_filter :authenticate_user!
  layout "profile"

  def index
    @results = Array.new
    # @results = ThinkingSphinx.search params[:q]
    @results = Activity.search(params[:q])
    @q = params[:q]
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_activities.html.haml
.activity.card.row
  .span2
    .thumbnail
      = link_to (image_tag activity.card), activity
  .span5
    .top
      %span.name= link_to highlight(activity.title, @q), activity
    .center
      =sanitize(highlight(truncate_html(activity.description,:length=>100), @q), :attributes => %w(id class style href _cke_saved_href title alt width height))
    .bottom
      %span.time
        = l activity.start_at, :format => :short
      %span.location
        = activity.location.truncate(20)
      %span.group
        = t '.from'
        = link_to activity.group.name.truncate(20), activity.group
      %span.meta
        = link_to (t '.like', :count => activity.fans.count), activity_circle_path(activity,activity.fan_circle)
        = "|"
        = link_to (t '.join', :count => activity.members.count), activity_circle_path(activity,activity.member_circle)
        = "|"
        = link_to (t '.comment', :count => activity.comments.count), activity.comments.first||activity_path(activity,:anchor=>'new-comment')

app/views/search/_groups.html.haml
.group.card.row
  .span2
    .thumbnail
      = link_to (image_tag group.card), group
  .span5
    .top
      %span.name= link_to highlight(group.name, @q), group
      %span.category= t group.category.name, :scope => :category
    .center
      = sanitize(highlight(group.introduction, @q), :attributes => %w(id class style href _cke_saved_href title alt width height)) 
    .bottom
      %span.founded
        = l group.founded_at
        = t '.founded'
      %span.admin
        = t :group_boss
        = link_to group.boss.name, group.boss
      %span.meta
        = link_to (t '.like', :count => group.fans.count), group_circle_path(group,group.fan_circle)
        = "|"
        = link_to (t '.join', :count => group.members.count), group_circle_path(group,group.member_circle)
        = "|"
        = link_to (t '.activities', :count => group.activities.count), group_activities_path(group)
        = "|"
        = link_to (t '.comments', :count => group.comments.count), group.comments.first ||group_path(group,:anchor=>'new-comment')

app/views/search/_profiles.html.haml
-user = profile.user
.profile.card.row
  .span1
    .avatar
      = link_to (image_tag profile.card), profile.card
  .span6
    .top
      %span.name= (highlight profile.name, @q), profile
    .center
      =sanitize(truncate_html(user.profile.description,:length=>100), :attributes => %w(id class style href _cke_saved_href title alt width height))
    .bottom
      %span.meta
        = link_to (t '.follows', :count => user.follows.count), users_profile_path(user)
        = "|"
        = link_to (t '.fans', :count => user.fans.count), users_profile_path(user)
        = "|"
        = link_to (t '.groups', :count => user.groups.count), profile_path(user)
        = "|"
        = link_to (t '.activities', :count => user.activities.count), profile_path(user)

app/views/search/index.html.haml
- if @results.empty?
  .alert.alert-info
    = link_to 'x', '', :class => 'close', 'data-dismiss' => 'alert'
    = t '.empty'
- else
  .content.index
    - @results.each do |result|
      - case result
      - when Group
        = render :partial => 'groups', :locals => { :group => result }
      - when Activity
        = render :partial => 'activities', :locals => { :activity => result }
      - when Profile
        = render :partial => 'profiles', :locals => { :profile => result }