config/routes.rb
Platform::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" } do
   get 'users/sign_out' => "devise/sessions#destroy"
   get 'users/sign_in' => "site#index"
  end

  get 'site/newsfeeds'
  
  get "admin" => "admin#index"

  mailboxes_for :users
  
  get "home" => "site#home"

  mount Ckeditor::Engine => '/ckeditor'

  post "search" => "search#index"

  resources :feedbacks

  namespace :admin do
    resources :forms
    get "members/index"
    post "members/edit"
    get "groups/index"
    post "groups/edit"
    get "activities/index"
    post "activities/edit"
    post "activities/change_group"
  end

  namespace :form do 
    resources :second_building_applications do 
      member do
        post :approve
        post :reject
      end
    end
  end

  resources :profiles do
    member do
      get 'like'
      get 'unlike'
      get 'users'
      put 'update_status'
    end
    collection do 
      get 'token'
    end
  end

  resources :groups do
    collection do
      get 'wall'
    end
    member do
      get 'join'
      get 'exit'
      get 'like'
      get 'unlike'
      get 'description'
      get 'history'
      get 'organization'
      get 'activities'
      get 'comments'
      get 'members'
      get 'sms' => 'sms#index'
      post 'sms/push' => 'sms#push'
      namespace :admin do
        get 'members'
        get 'forms'
        get 'introduction'
        get 'description'
        get 'history'
        get 'organization'
        post 'members' => 'groups#edit_members'
      end
      namespace :form do
        get 'second_building/new' => 'second_building_applications#new'
      end
    end
    resources :circles do
      collection do
        post 'change_boss/:user_id' => 'circles#change_boss'
        post 'update/:user_id' => 'circles#update_user'
        post 'approve/:user_id' => 'circles#approve'
        post 'reject/:user_id' => 'circles#reject'
        post 'kickout/:user_id' => 'circles#kickout'
      end
    end
    resources :activities, :only => [:new, :create]
  end

  resources :activities do
    collection do
      get 'tag_cloud'
      get 'wall'
    end
    member do
      get 'join'
      get 'exit'
      get 'unlike'
      get 'like'
    end
    resources :blogs 

    resources :pictures do
      member do
        get 'show_gallery'
        get 'load'
      end
    end
    resources :albums 
    resources :circles do
      collection do
        post 'update/:user_id' => 'circles#update_user'
        post 'change_boss/:user_id' => 'circles#change_boss'
        post 'approve/:user_id' => 'circles#approve'
        post 'reject/:user_id' => 'circles#reject'
        post 'kickout/:user_id' => 'circles#kickout'
      end
    end
  end

  resources :comments, :only => [:create, :destroy]

  get 'circles/:id/message' => 'circles#message', :as=>'message_circle'

  get 'tags' => 'application#tags'

  root :to => "site#index"

end

app/models/group.rb
class Group < ActiveRecord::Base

  validates_presence_of :category_id
  validates_presence_of :name
  validates_uniqueness_of :name

  scope :category, lambda{|cat| where("category_id = ?", cat.id)}
  default_scope where("groups.status != ?", Constant::Blocked)

  acts_as_taggable
  acts_as_commentable

  is_impressionable

  belongs_to :category
  belongs_to :boss, :class_name=>"User"

  has_many :activities, :dependent => :destroy
  has_many :second_building_applications, :class_name => "Form::SecondBuildingApplication"
  has_many :albums, :as => :imageable
  has_many :sms, :class_name => "Sms"
  has_many :circles,    :as => :owner, :dependent => :destroy
  has_many :users,      :through => :circles

  has_attached_file :logo, :styles => { :medium => "360x268#", :card => "160x120#", :thumb => "64x64#" }, :default_url => "missing_:style.jpg"

  after_create :initialize_circles
  after_save :get_py

  def initialize_circles
    circles.create(:name => 'admin',      :status => Constant::Admin)
    circles.create(:name => 'member',     :status => Constant::Member)
    circles.create(:name => 'fan',        :status => Constant::Fan)
    circles.create(:name => 'applicant',  :status => Constant::Approving, :public=>false)
  end

  def members
    member_circle.users
  end

  def admins
    admin_circle.users
  end

  def fans
    fan_circle.users
  end

  def applicants
    applicant_circle.users
  end

  def member_circle
    circles.member.first
  end

  def admin_circle
    circles.admin.first
  end

  def fan_circle
    circles.fan.first
  end

  def applicant_circle 
    circles.applicant.first
  end

  def subscribers
    members | admins | followers
  end

  def get_py
    if self.pyname!=Hz2py.do(name)
      self.pyname = Hz2py.do(name)
      save
    end
  end

  def role(user)
    r = ""
    if boss == user
      r = I18n.t('group_boss')
    elsif admins.include?(user)
      r = I18n.t('group_admin')
    elsif members.include?(user)
      r = I18n.t('group_members')
    end
    r
  end

  def self.update_points
    Group.all.each do |group|
      group.points = group.pv + group.members
      group.activities.each do |activity|
        group.points += activity.points
      end
      group.save
    end
  end

  def self.hot
    Group.order("points DESC")
  end


  def self.joined(user)
    scoped.select{|a| a.members.include? user}
  end

  def self.liked(user)
    scoped.select{|a| a.fans.include? user}
  end

  def card
    logo.url(:card)
  end

  def thumb
    logo.url(:thumb)
  end

  def medium
    logo.url(:medium)
  end

  def original
    logo.url(:original)
  end

  def pv
    impressionist_count(:filter => :session_hash)
  end

  def announce
    announcement.nil? ? I18n.t('announce_empty') : announcement
  end

  define_index do
    # fields
    indexes :name, :sortable => true
    indexes :introduction
    
    # attributes
    has :created_at, :updated_at

    set_property :delta => true
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  layout :resolve_layout

  private
  def resolve_layout
    case action_name
    when "index"
      "admin"
    else
      "groups_show"
    end
  end

  public
  def index
    authorize! :admin, :backend

    if params[:filter] == "approving"
      filter = Constant::Approving
    elsif params[:filter] == "approved"
      filter = Constant::Approved
    elsif params[:filter] == "blocked"
      filter = Constant::Blocked
    elsif params[:filter] == "rejected"
      filter = Constant::Rejected
    else
      filter = nil
    end

    if filter.nil?
      @groups = Group.unscoped.paginate(:page => params[:page], :per_page => 15)
    else
      @groups = Group.unscoped.where(:status => filter).paginate(:page => params[:page], :per_page => 15)
    end
  end

  def members
    @group = Group.unscoped.find(params[:id])
    authorize! :admin, @group

    @tenders = @group.tenders
    @admins  = @group.admins
    @members = @group.members
  end

  def forms
    @group = Group.unscoped.find(params[:id])
    authorize! :admin, @group

    @second_buildings = @group.second_building_applications
  end

  def edit_members
    @group = Group.unscoped.find(params[:id])
    authorize! :admin, @group

    member = params[:member_id]
    relation = UserGroup.unscoped.f(params[:id], member)
    relation.set(params[:status][member])
    render :nothing => true
  end

  def description
    @group = Group.unscoped.find(params[:id])
    authorize! :admin, @group
  end

  def introduction
    @group = Group.unscoped.find(params[:id])
    authorize! :admin, @group
  end

  def history
    @group = Group.unscoped.find(params[:id])
    authorize! :admin, @group
  end

  def organization
    @group = Group.unscoped.find(params[:id])
    authorize! :admin, @group
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  layout :resolve_layout
  impressionist :actions => [:show], :unique => [:impressionable_type, :impressionable_id, :session_hash]

  private
  def resolve_layout
    case action_name
    when "index", "wall"
      "groups_index"
    when "new", "create"
      "admin"
    else
      "groups_show"
    end
  end
  

  public
  # GET /groups
  # GET /groups.json



  def index
    if params[:sort] == "latest"
      sort = "created_at DESC"
    elsif params[:sort] == "founded"
      sort = "founded_at DESC"
    else
      sort = "created_at DESC"
    end

    if params[:filter] == "category"
      @groups = Group.category(Category.find(params[:id])).order(sort)
    elsif params[:filter] == "join"
      @groups = Group.order(sort).joined(current_user)
    elsif params[:filter] == "like"
      @groups = Group.order(sort).liked(current_user)
    else
      @groups = Group.order(sort).all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])
    @more = @group.activities.count > 3
    @core = @group.comments.recent.count > 8
    @members = @group.members
    @mere = @group.members.count > 14

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    authorize! :admin, :site
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @form = true
    @group = Group.find(params[:id])
    authorize! :admin, @group

    case params[:q]
    when '1'
      render :action => :edit_introduction
    when '2'
      render :edit_description
    when '3'
      render :edit_history
    when '4'
      render :edit_organization
    when '5'
      redirect_to @group
    else
      render :edit
    end
  end

  # POST /groups
  # POST /groups.json
  
  def create
    authorize! :admin, :site

    @group = Group.new(params[:group])
    @group.status = Constant::Approving
    @group.boss_id = current_user.id

    respond_to do |format|
      if @group.save
        @group.admin_circle.add(current_user)
        @group.member_circle.add(current_user)
        format.html { redirect_to :action => 'edit', :id => @group.id, :q => 1 }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])
    authorize! :admin, @group

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { 
          if params[:q].nil?
            redirect_to @group
          else
            redirect_to :action => 'edit', :id => @group.id, :q => params[:q]
          end
        }
        format.json { head :ok }
        format.js   { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    authorize! :admin, :site

    @group = Group.find(params[:id]) 
    @group.destroy 
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end

  def like
    @group = Group.find(params[:id])
    authorize! :like, @group

    @group.fan_circle.add(current_user)
  end

  def unlike
    @group = Group.find(params[:id])
    authorize! :unlike, @group

    @group.fan_circle.remove(current_user)
  end

  def join
    @group = Group.find(params[:id])
    authorize! :join, @group

    @group.applicant_circle.add(current_user)
  end

  def exit
    @group = Group.find(params[:id])
    authorize! :exit, @group

    @group.member_circle.remove(current_user)
    render :join
  end

  def description
    @group = Group.find(params[:id])
    @crumbs.push({:name=>@group.name, :path=>group_path(@group)})
    @crumbs.push({:name=>"groups.description.header", :path=>description_group_path(@group)})

  end

  def history
    @group = Group.find(params[:id])
    @crumbs.push({:name=>@group.name, :path=>group_path(@group)})
    @crumbs.push({:name=>"groups.history.header", :path=>organization_group_path(@group)})

  end

  def organization
    @group = Group.find(params[:id])
    @crumbs.push({:name=>@group.name, :path=>group_path(@group)})
    @crumbs.push({:name=>"groups.organization.header", :path=>organization_group_path(@group)})

  end

  def activities
    @navi = "activities/navi"
    @group = Group.find(params[:id])
    @activities = @group.activities
    @crumbs.push({:name=>@group.name, :path=>group_path(@group)})
    @crumbs.push({:name=>"groups.activities.title", :path=>group_activities_path(@group)})
  end

  def comments
    @group = Group.find(params[:id])
    @comments = @group.comments.recent
  end

  def wall
    @groups = Group.all
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_activities.html.haml
.activities
  %span.label.label-info
    = t :activity
  %div
    - if @group.activities.empty?
      .alert.alert-info
        = link_to 'x', '', :class => 'close', 'data-dismiss' => 'alert'
        = t '.warn'
    - else
      = render :partial => 'activities/card', :collection => @group.activities.last(3), :as => :activity
  .more.row
    - if @more
      = link_to (t '.more'), activities_group_path, :class => 'btn btn-info span3 offset2'

app/views/groups/_announcement.html.haml
.announcement.well
  = @group.announce

app/views/groups/_board.html.haml
.group.board.row.alert-info
  = render :partial => 'side', :locals => { :group => group, :board => true }
  = render :partial => 'info', :locals => { :group => group }

app/views/groups/_card.html.haml
.group.card.row
  .span2
    .thumbnail
      = link_to (image_tag group.card), group
  .span5
    .top
      %span.name= link_to group.name, group
      %span.category= t group.category.name, :scope => :category
    .center
      = sanitize(group.introduction, :attributes => %w(id class style href _cke_saved_href title alt width height)) 
    .bottom
      %span.founded
        = l group.founded_at
        = t '.founded'
      %span.admin
        = t :group_boss
        = link_to group.boss.name, group.boss
      %span.meta
        = link_to (t '.like', :count => group.fans.count), group_circle_path(group,group.fan_circle)
        = "|"
        = link_to (t '.join', :count => group.members.count), group_circle_path(group,group.member_circle)
        = "|"
        = link_to (t '.activities', :count => group.activities.count), group_activities_path(group)
        = "|"
        = link_to (t '.comments', :count => group.comments.count), group.comments.first ||group_path(group,:anchor=>'new-comment')

app/views/groups/_comments.html.haml
.comments
  %span.label.label-info
    = t :comment
  = render :partial => "share/comments", :locals => { :object => @group }

app/views/groups/_like.html.haml
%span.like
  - if can? :like, group
    = link_to (t '.like'), like_group_path(group), :remote => true
  - else
    = link_to (t '.unlike'), unlike_group_path(group), :remote => true

app/views/groups/_members.html.haml
.tabbable.groups
  %ul.nav.nav-tabs
    %li.active
      = link_to (t '.members'), '#members', 'data-toggle' => 'tab'
    %li
      = link_to (t '.fans'), '#fans', 'data-toggle' => 'tab'
  .tab-content
    #members.tab-pane.active
      .thumbnails
        - @group.members.each do |member|
          .span1
            = link_to (image_tag member.thumb), member
            = link_to member.name.truncate(8), member.profile
    #fans.tab-pane
      .thumbnails
        - @group.fans.each do |member|
          .span1
            = link_to (image_tag member.thumb), member
            = link_to member.name.truncate(8), member.profile

app/views/groups/edit.html.haml
.btn-group
  = link_to (t '.intr'), introduction_admin_group_path, :class => 'btn'
  = link_to (t '.desc'), description_admin_group_path, :class => 'btn'
  = link_to (t '.hist'), history_admin_group_path, :class => 'btn'
  = link_to (t '.orga'), organization_admin_group_path, :class => 'btn'
.edit-group
  = form_for @group, :html => {:class => 'form-horizontal'} do |f|
    %fieldset
      %legend
        = t '.title'
      .control-group
        = f.label :name, (t '.name'), :class => 'control-label'
        .controls
          = f.text_field :name
      .control-group
        = f.label :slogan, (t '.slogan'), :class => 'control-label'
        .controls
          = f.text_field :slogan
      .control-group
        = f.label :email, (t '.email'), :class => 'control-label'
        .controls
          = f.text_field :email
      .control-group
        = f.label :founded_at, (t '.founded'), :class => 'control-label'
        .controls
          = f.date_select :founded_at, { :start_year => 1980 }, { :class => 'span1' }
      .control-group
        = f.label :logo, (t '.logo'), :class => 'control-label'
        .controls
          = f.file_field :logo
      .control-group
        = f.label :category, (t '.category'), :class => 'control-label'
        .controls
          = f.collection_select :category_id, Category.all, :id, :translated_name
      -if @group.errors.any?
        #error_explanation
          %ul
            - @group.errors.full_messages.each do |msg|
              %li= msg
      .form-actions
        %button.btn.btn-primary{:type => 'submit'}
          = t '.new'
        %button.btn
          = t '.cancel'

app/views/groups/edit_history.html.haml
.page-header
  %h1
    = t '.title'
= form_for @group do |f|
  = hidden_field_tag 'q', '4'
  = f.cktext_area :history, :height => 300
  .button-wrapper
    = f.submit (t '.save'), { :class => 'btn btn-primary' }

app/views/groups/edit_organization.html.haml
.page-header
  %h1
    = t '.title'
= form_for @group do |f|
  = hidden_field_tag 'q', '5'
  = f.cktext_area :organization, :height => 300
  .button-wrapper
    = f.submit (t '.save'), { :class => 'btn btn-primary' }

app/views/groups/history.html.haml
= render :partial => 'share/breadcrumbs'
.page-header
  %h1= t '.header'
.history
  = sanitize( @group.history, :attributes => %w(id class style src href _cke_saved_href title alt width height)) 

app/views/groups/like.js.erb
$(".like").replaceWith("<%= escape_javascript(render :partial => 'groups/like', :object => @group, :as => :group ) %>");

app/views/groups/members.html.haml
.members
  .back
    = link_to (t '.back'), @group
  .title
    = t '.title', :name => @group.name
  .box
    %ul
      - @members.each do |member|
        %li
          .avatar= image_tag member.url
          .name= link_to member.name, member.profile

app/views/groups/show.html.haml
= render :partial => 'board', :object => @group, :as => :group
= render :partial => 'activities'
= render :partial => 'comments'