config/routes.rb
Platform::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" } do
   get 'users/sign_out' => "devise/sessions#destroy"
   get 'users/sign_in' => "site#index"
  end

  get 'site/newsfeeds'
  
  get "admin" => "admin#index"

  mailboxes_for :users
  
  get "home" => "site#home"

  mount Ckeditor::Engine => '/ckeditor'

  post "search" => "search#index"

  resources :feedbacks

  namespace :admin do
    resources :forms
    get "members/index"
    post "members/edit"
    get "groups/index"
    post "groups/edit"
    get "activities/index"
    post "activities/edit"
    post "activities/change_group"
  end

  namespace :form do 
    resources :second_building_applications do 
      member do
        post :approve
        post :reject
      end
    end
  end

  resources :profiles do
    member do
      get 'like'
      get 'unlike'
      get 'users'
      put 'update_status'
    end
    collection do 
      get 'token'
    end
  end

  resources :groups do
    collection do
      get 'wall'
    end
    member do
      get 'join'
      get 'exit'
      get 'like'
      get 'unlike'
      get 'description'
      get 'history'
      get 'organization'
      get 'activities'
      get 'comments'
      get 'members'
      get 'sms' => 'sms#index'
      post 'sms/push' => 'sms#push'
      namespace :admin do
        get 'members'
        get 'forms'
        get 'introduction'
        get 'description'
        get 'history'
        get 'organization'
        post 'members' => 'groups#edit_members'
      end
      namespace :form do
        get 'second_building/new' => 'second_building_applications#new'
      end
    end
    resources :circles do
      collection do
        post 'change_boss/:user_id' => 'circles#change_boss'
        post 'update/:user_id' => 'circles#update_user'
        post 'approve/:user_id' => 'circles#approve'
        post 'reject/:user_id' => 'circles#reject'
        post 'kickout/:user_id' => 'circles#kickout'
      end
    end
    resources :activities, :only => [:new, :create]
  end

  resources :activities do
    collection do
      get 'tag_cloud'
      get 'wall'
    end
    member do
      get 'join'
      get 'exit'
      get 'unlike'
      get 'like'
    end
    resources :blogs 

    resources :pictures do
      member do
        get 'show_gallery'
        get 'load'
      end
    end
    resources :albums 
    resources :circles do
      collection do
        post 'update/:user_id' => 'circles#update_user'
        post 'change_boss/:user_id' => 'circles#change_boss'
        post 'approve/:user_id' => 'circles#approve'
        post 'reject/:user_id' => 'circles#reject'
        post 'kickout/:user_id' => 'circles#kickout'
      end
    end
  end

  resources :comments, :only => [:create, :destroy]

  get 'circles/:id/message' => 'circles#message', :as=>'message_circle'

  get 'tags' => 'application#tags'

  root :to => "site#index"

end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
	                  :styles => { :content => '800>', :thumb => '118x100#' }
	
	validates_attachment_size :data, :less_than => 2.megabytes
	validates_attachment_presence :data
	
	def url_content
	  url(:content)
	end
end

app/models/picture.rb
class Picture < ActiveRecord::Base

  acts_as_taggable
  acts_as_commentable
  
  belongs_to :album
  belongs_to :user
  has_attached_file :photo, :styles => { :big=>"600x600>",:medium => "360x268#", :small => "160x120#", :thumb => "64x64#" }
  
  after_create :new_event

  def new_event
    Event.create(:subject_type=>"User",:subject_id=>user_id,:action=>:upload,:object_type=>"Picture",:object_id=>id)
  end

  def name
    album.title + "(#{album.imageable.name})"
  end

  def bare_name
    album.title
  end

  def url(size=:thumb)
    photo.url(size)
  end

  def big
    url(:big)
  end

  def medium
    url(:medium)
  end

  def small
    url(:small)
  end

  def thumb
    url(:thumb)
  end

  def imageable
    album.imageable
  end

  def prev
    album.pictures[(album.pictures.find_index(self)-1) % album.pictures.count]
  end

  def next
    album.pictures[(album.pictures.find_index(self)+1) % album.pictures.count]
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :authenticate_user!
  layout 'activities_show'

  # GET /pictures
  # GET /pictures.json
  def index
    @activity = Activity.find(params[:activity_id])
    @group = @activity.group
    @pictures = @activity.pictures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])
    @activity = @picture.album.imageable
    @group = @activity.group

    respond_to do |format|
      format.html { render 'show' }
      format.json { render json: @picture }
    end
  end

  def show_gallery
    @picture = Picture.find(params[:id])
    @activity = @picture.album.imageable
    @group = @activity.group

    respond_to do |format|
      format.html { render 'show_gallery',:layout=>false }
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @activity = Activity.find(params[:activity_id])
    @group = @activity.group
    @picture = Picture.new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])
    @picture.user = current_user
    @activity = @picture.album.imageable

    respond_to do |format|
      if @picture.save
        format.html { redirect_to [@activity, @picture], notice: 'Picture was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to [@picture.imageable, @picture], notice: 'Picture was successfully updated.' }
        format.json { respond_with_bip(@picture) }
      else
        format.html { render action: "edit" }
        format.json { respond_with_bip(@picture) }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @activity = @picture.imageable
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to activity_pictures_path(@activity) }
      format.json { head :ok }
    end
  end


  def load
    @picture = Picture.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper
  def destroy_activity_picture_path(activity, picture)
    url_for(:controller=>:pictures, :action=>:destroy)
  end
end

app/views/pictures/_form.html.haml
.need_hide.new-album
  = form_for([@activity, @album]) do |f|
    .field
      = f.label :title,(t "albums.title")
      = f.text_field :title, :placeholder=>(t "albums.title")
      = hidden_field_tag :activity_id,@activity.id
    .button-wrapper
      = f.submit(t :new_album) 
    .back= link_to (t ".photo"), "javascript:$('.new-album').toggle();$('.new-picture').toggle();"      

  .clear
.new-picture
  = form_for [@activity ,@picture], :html => { :multipart => true }do |f|
    - if @picture.errors.any?
      #error_explanation
        %h2
          = pluralize(@picture.errors.count, "error")
          prohibited this picture from being saved:
        %ul
          - @picture.errors.full_messages.each do |msg|
            %li= msg
    .field
      = f.label :album, (t :album)
      = collection_select(:picture, :album_id, @activity.albums, :id, :title, :selected => params[:album_id])
      = link_to (t ".album"), "javascript:$('.new-album').toggle();$('.new-picture').toggle();"      
    .field.area
      = f.label :remark,(t :remark)
      = f.text_area :remark, :rows => 1
    .field
      = f.label :photo, (t '.photo')
      = f.file_field :photo
    .actions
      = f.submit(t :upload)

app/views/pictures/_navi.html.haml
= link_to (t 'share.navi.home'), home_path
= link_to (t 'share.navi.group'), groups_path
= link_to (t '.activity'), activity_path(@activity)
- if !@picture.nil?
  = link_to (t '.list'), activity_pictures_path(@activity)
- if (can? :admin, @activity) 
  = link_to (t '.new'), new_activity_picture_path(@activity,:album_id=>(@album||0))

app/views/pictures/_picture.html.haml
.box.picture
  .box-header
    .avatar= link_to(image_tag(@picture.user.url(:small)),@picture.user)
    .info 
      .title= link_to(@picture.album.title, @picture.album, :class=>"title")
      .uploader
        %span.user-name= link_to(@picture.user.name,@picture.user)
        %span.post-in= (t :post) + (t :in)
        %span.time= l @picture.created_at
    .clear
  .box-content
    =link_to image_tag(@picture.url(:big)),@picture.url(:original), :target=>"_blank"
  .textarea-wrapper
    =best_in_place_if (can? :admin, @picture), @picture, :remark, :type => :textarea, :nil => t("Click me to add remark!"), :display_with => :simple_format
    :javascript
      $(function(){$(".best_in_place").best_in_place();});
  .navi
    = link_to (t ".prev"),load_picture_path(@picture.prev),:remote=>true
    = "/"
    = link_to (t ".next"),load_picture_path(@picture.next),:remote=>true
.picture.comments
  .list
    = render :partial => "share/comments", :locals => { :object => @picture }

app/views/pictures/edit.html.haml
%h1 Editing picture
= render 'form'
= link_to 'Show', @picture
|
\#{link_to 'Back', pictures_path}

app/views/pictures/index.html.haml
.activity-pictures
  .back= link_to t(".back"), @activity
  .title= t ".title", :name => @activity.name
-if @pictures.empty?
  .box.no-content
    =t (".empty")
-else
  .box.detail
    .box-body
      %ul.album-pictures
        - @activity.pictures.each do |pic|
          %li
            .image-pic=link_to image_tag(pic.url(:medium)), pic
            .image-mani
              - if !pic.remark.empty?
                .image-remark= pic.remark
    .clear

app/views/pictures/load.js.erb
$(".main").html('<%= escape_javascript(render :partial=>"picture")%>');

app/views/pictures/new.html.haml
= form_for [@activity ,@picture], :html => { :multipart => true, :class => "form-horizontal" } do |f|
  %fieldset
    %legend
      = t '.title'
    .control-group
      = f.label :album, (t :album), :class => 'control-label'
      .controls
        = collection_select(:picture, :album_id, @activity.albums, :id, :title, :selected => params[:album_id])
        = link_to (t ".album"), '#album-modal', :class => "btn", 'data-toggle' => 'modal'
    .control-group
      = f.label :remark,(t :remark), :class => 'control-label'
      .controls
        = f.text_area :remark, :rows => 1
    .control-group
      = f.label :photo, (t '.photo'), :class => 'control-label'
      .controls
        = f.file_field :photo
    .form-actions
      = f.submit t(:upload), :class => 'btn btn-primary'

.modal.fade#album-modal
  = form_for [@activity, @album], :html => { :class => "form-horizontal" } do |f|
    .modal-header
      = link_to 'x', '#', :class => 'close', 'data-dismiss' => 'modal'
      %h3
        = t '.album'
    .modal-body
      .control-group
        = f.label :title, t('.name'), :class => 'control-label'
        .controls
          = f.text_field :title
        = hidden_field_tag :activity_id, @activity.id
    .modal-footer
      = f.submit t('.save'), :class => 'btn btn-primary'
      = link_to t('.close'), '#', :class => 'btn', 'data-dismiss' => 'modal'

app/views/pictures/show.html.haml
.page-header
  %h1
    = @picture.album.title
.picture-wrapper
  .picture
    =link_to image_tag(@picture.url(:big)),@picture.url(:original), :target=>"_blank"
  .remark
    =best_in_place_if (can? :admin, @picture), @picture, :remark, :type => :textarea, :nil => t("Click me to add remark!"), :display_with => :simple_format
    :javascript
      $(function(){$(".best_in_place").best_in_place();});
  .navi
    = link_to (t ".prev"),picture_path(@picture.prev)
    = "/"
    = link_to (t ".next"),picture_path(@picture.next)
.comments
  = render :partial => "share/comments", :locals => { :object => @picture }

app/views/pictures/show_gallery.html.haml
.picture-pop
  =link_to image_tag(@picture.url(:original)), @picture