config/routes.rb
Platform::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" } do
   get 'users/sign_out' => "devise/sessions#destroy"
   get 'users/sign_in' => "site#index"
  end

  get 'site/newsfeeds'
  
  get "admin" => "admin#index"

  mailboxes_for :users
  
  get "home" => "site#home"

  mount Ckeditor::Engine => '/ckeditor'

  post "search" => "search#index"

  resources :feedbacks

  namespace :admin do
    resources :forms
    get "members/index"
    post "members/edit"
    get "groups/index"
    post "groups/edit"
    get "activities/index"
    post "activities/edit"
    post "activities/change_group"
  end

  namespace :form do 
    resources :second_building_applications do 
      member do
        post :approve
        post :reject
      end
    end
  end

  resources :profiles do
    member do
      get 'like'
      get 'unlike'
      get 'users'
      put 'update_status'
    end
    collection do 
      get 'token'
    end
  end

  resources :groups do
    collection do
      get 'wall'
    end
    member do
      get 'join'
      get 'exit'
      get 'like'
      get 'unlike'
      get 'description'
      get 'history'
      get 'organization'
      get 'activities'
      get 'comments'
      get 'members'
      get 'sms' => 'sms#index'
      post 'sms/push' => 'sms#push'
      namespace :admin do
        get 'members'
        get 'forms'
        get 'introduction'
        get 'description'
        get 'history'
        get 'organization'
        post 'members' => 'groups#edit_members'
      end
      namespace :form do
        get 'second_building/new' => 'second_building_applications#new'
      end
    end
    resources :circles do
      collection do
        post 'change_boss/:user_id' => 'circles#change_boss'
        post 'update/:user_id' => 'circles#update_user'
        post 'approve/:user_id' => 'circles#approve'
        post 'reject/:user_id' => 'circles#reject'
        post 'kickout/:user_id' => 'circles#kickout'
      end
    end
    resources :activities, :only => [:new, :create]
  end

  resources :activities do
    collection do
      get 'tag_cloud'
      get 'wall'
    end
    member do
      get 'join'
      get 'exit'
      get 'unlike'
      get 'like'
    end
    resources :blogs 

    resources :pictures do
      member do
        get 'show_gallery'
        get 'load'
      end
    end
    resources :albums 
    resources :circles do
      collection do
        post 'update/:user_id' => 'circles#update_user'
        post 'change_boss/:user_id' => 'circles#change_boss'
        post 'approve/:user_id' => 'circles#approve'
        post 'reject/:user_id' => 'circles#reject'
        post 'kickout/:user_id' => 'circles#kickout'
      end
    end
  end

  resources :comments, :only => [:create, :destroy]

  get 'circles/:id/message' => 'circles#message', :as=>'message_circle'

  get 'tags' => 'application#tags'

  root :to => "site#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  validates_presence_of :group_id
  validates_presence_of :location
  validates_presence_of :title

  default_scope where("activities.status != ?", Constant::Blocked)

  acts_as_taggable
  acts_as_commentable

  is_impressionable

  belongs_to :group

  belongs_to :boss, :class_name => "User"

  scope :category, lambda{|cat| joins(:group).where("groups.category_id = ?", cat.id)}

  has_many :albums, :as => :imageable
  has_many :pictures, :through => :albums
  has_many :blogs, :dependent => :destroy
  has_many :circles, :as => :owner, :dependent => :destroy
  has_many :users, :through => :circles

  has_attached_file :poster, :styles => { :medium => "570x330#",:card => "160x120#", :thumb => "64x64#" }, :default_url => "missing_:style.jpg"
  has_attached_file :banner, :styles => { :medium => "576x320#", :banner => "180x100#" }, :default_url => "missing_:style.jpg"

  after_create :initialize_circles
  after_create :new_event
  after_create :new_album
  after_save :get_py

  def initialize_circles
    circles.create(:name => 'admin',      :status => Constant::Admin)
    circles.create(:name => 'member',     :status => Constant::Member)
    circles.create(:name => 'fan',        :status => Constant::Fan)
    circles.create(:name => 'applicant',  :status => Constant::Approving, :public=>false)
  end

  def new_event
    Event.create(:subject_type => "Group", :subject_id => group.id, :action => "create", :object_type => "Activity", :object_id => id)
  end

  def new_album
  end

  def members
    member_circle.users
  end

  def admins
    admin_circle.users
  end

  def fans
    fan_circle.users
  end

  def applicants
    applicant_circle.users
  end

  def member_circle
    circles.member.first
  end

  def admin_circle
    circles.admin.first
  end

  def fan_circle
    circles.fan.first
  end

  def applicant_circle
    circles.applicant.first
  end

  def subscribers
    members | admins | fans
  end

  def get_py
    if self.pyname!=Hz2py.do(name)
      self.pyname = Hz2py.do(name)
      save
    end
  end

  def url
    poster.url(:thumb)
  end

  def name
    title || ""
  end

  def thumb
    poster.url(:thumb)
  end

  def card
    poster.url(:card)
  end

  def medium
    poster.url(:medium)
  end

  def self.update_points
    Activity.all.each do |activity|
      activity.points = activity.pv + activity.members.count
                        + activity.fans.count 
                        + activity.blogs.count * 5 
                        + activity.pictures.count * 3
    end
  end

  def self.hot
    Activity.order("points DESC")
  end


  def self.joined(user)
    scoped.select{|a| a.members.include? user}
  end

  def self.liked(user)
    scoped.select{|a| a.fans.include? user}
  end

  def pv
    impressionist_count(:filter => :session_hash)
  end

  def role(user)
    r = ""
    if boss == user
      r = I18n.t('activity_boss')
    elsif admins.include?(user)
      r = I18n.t('activity_admin')
    elsif members.include?(user)
      r = I18n.t('activity_member')
    end
    r
  end

  define_index do
    indexes :title, :sortable => true
    indexed :description

    has :start_at, :end_at
    set_property :delta => true
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :authenticate_user!
  layout :resolve_layout
  impressionist :actions => [:show], :unique => [:impressionable_type, :impressionable_id, :session_hash]

  private
  def resolve_layout
    case action_name
    when "index", "wall"
      "activities_index"
    when "new"
      "groups_show"
    else
      "activities_show"
    end
  end

  public
  #layout 'activities'
  # GET /activities
  # GET /activities.json
  def index

    @hots = Activity.first(5)

    if params[:sort] == "latest"
      sort = "created_at DESC"
    elsif params[:sort] == "pop"
      sort = "points DESC"
    else
      sort = "created_at DESC"
    end

    if params[:tags]
      @activities = Activity.tagged_with(params[:tags])
      @tags = params[:tags].split(',').map(&:strip).reject(&:blank?).map{ |e| {:name => e} }
    else
      @activities = Activity
    end
    
    if params[:filter] == "category"
      @activities = @activities.category(Category.find(params[:id])).order(sort)
    elsif params[:filter] == "join"
      @activities = @activities.order(sort).joined(current_user)
    elsif params[:filter] == "like"
      @activities = @activities.order(sort).liked(current_user)
    else
      @activities = @activities.order(sort).limit(50)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end


  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])
    @group = @activity.group
    @bore = @activity.blogs.count > 4
    @pore = @activity.pictures.count > 6
    @core = @activity.comments.recent.count > 6
    if @activity.admins.include?(current_user)
      @is_admin = true
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @group = Group.find(params[:group_id])
    authorize! :admin, @group

    @activity = @group.activities.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
    @group = @activity.group

    authorize! :admin, @activity
  end

  # POST /activities
  # POST /activities.json
  def create
    @group = Group.find(params[:activity][:group_id])
    authorize! :admin, @group

    @activity = Activity.new(params[:activity])
    @activity.status = Constant::Approving
    @activity.boss = current_user

    respond_to do |format|
      if @activity.save
        @activity.admin_circle.add(current_user)
        @activity.member_circle.add(current_user)
        @activity.boss=current_user
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])
    authorize! :admin, @activity

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated' }
        format.json { head :ok }
        format.js { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    authorize! :admin, @activity

    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :ok }
    end
  end

  def like
    @activity = Activity.find(params[:id])
    authorize! :like, @activity
    @activity.fan_circle.add(current_user)

    head :ok
  end

  def unlike
    @activity = Activity.find(params[:id])
    authorize! :unlike, @activity
    @activity.fan_circle.remove(current_user)
    
    head :ok
  end

  def join
    @activity = Activity.find(params[:id])
    authorize! :join, @activity

    if @activity.public
      @activity.member_circle.add(current_user)
    else
      @activity.applicant_circle.add(current_user)
    end

    respond_to do |format|
      format.js
    end
  end

  def exit
    @activity = Activity.find(params[:id])
    authorize! :exit, @activity

    @activity.member_circle.remove(current_user)
    respond_to do |format|
      format.js { render 'join' }
    end
  end

  def tag_cloud
    @tags = Activity.tag_counts
  end

  def wall
    @activities = Activity.first(50)
  end
end

app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < ApplicationController
  layout "admin"

  def index
    authorize! :admin, :backend

    if params[:filter] == "approving"
      filter = Constant::Approving
    elsif params[:filter] == "approved"
      filter = Constant::Approved
    elsif params[:filter] == "blocked"
      filter = Constant::Blocked
    elsif params[:filter] == "rejected"
      filter = Constant::Rejected
    else
      filter = nil 
    end

    if filter.nil?
      @activities = Activity.unscoped.paginate(:page => params[:page], :per_page => 15)
    else
      @activities = Activity.unscoped.where(:status => filter).paginate(:page => params[:page], :per_page => 15)
    end
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper

  include ActsAsTaggableOn::TagsHelper

  def stime(activity)
    if activity.start_at.to_date == activity.end_at.to_date
      t("time:",:start_time=>activity.lstart_at,:end_time=>activity.lend_at(:only_time))
    elsif activity.start_at.year == activity.end_at.year
      t("time:",:start_time=>activity.lstart_at,:end_time=>activity.lend_at)  
    else
      t("time:",:start_time=>activity.lstart_at(:default),:end_time=>activity.lend_at(:default))
    end
  end

  def is_group_member(activity, user)
    if activity.group.members.include?(user)
      t "is_group_member"
    else
      t "not_group_member"
    end
  end

  def activity_is_public(activity)
    if activity.public?
      t "public"
    else
      t "not_public"
    end
  end

  def activity_status(activity)
    case activity.status
      when Constant::Approving
        t "approving"
      when Constant::Approved
        t "approved"
      when Constant::Blocked
        t "blocked"
      when Constant::Rejected
        t"reject"
    end
  end
end

app/helpers/admin/activities_helper.rb
module Admin::ActivitiesHelper
end

app/views/activities/_board.html.haml
.activity.board.row.alert-info
  = render :partial => 'side', :locals => { :activity => activity, :board => true }
  = render :partial => 'info', :locals => { :activity => activity, :board => true }

app/views/activities/_filter.html.haml
.filter-wrapper
  #filter-tag
    = form_tag "",:method=>:get do
      = text_field_tag :tags, "", :class => "tags-filter"
      #tags-json.hide= @tags.to_json
  .clear
  %ul.nav.nav-pills
    %li#filter-all.active
      = link_to (t '.all'), activities_path(:sort => params[:sort], :filter => 'all', :anchor=>"filter-all")
    %li#filter-like
      = link_to (t '.like'), activities_path(:sort => params[:sort], :filter => 'like', :anchor=>"filter-like")
    %li#filter-join
      = link_to (t '.join'), activities_path(:sort => params[:sort], :filter => 'join', :anchor=>"filter-join")
    %li#to-wall
      = link_to (t '.wall'), wall_activities_path(:anchor=>"to-wall")
    %li.dropdown#filter-category
      %a{ :class => 'dropdown-toggle', :href => '#', 'data-toggle' => 'dropdown' }
        = t '.category'
        %b.caret
      %ul.dropdown-menu
        - Category.all.each do |category|
          %li
            = link_to category.translated_name, activities_path(:sort => params[:sort], :filter => 'category', :id => category.id, :anchor=>"filter-category")
  .clear

app/views/activities/_hot.html.haml
.activity-hot
  .title
    = #t '.hot'
  .hot-cycle
    - Activity.hot.first(12).each_slice(4) do |activities|
      .pic
        - activities.each do |activity|
          = link_to (image_tag activity.card), activity

app/views/activities/_info.html.haml
.info.span5
  .title= activity.title
  .admin
    %span.group-name= link_to activity.group.name.truncate(20), activity.group
    %span= t :host
    %span= link_to activity.boss.profile.name, activity.boss.profile
    %span= t :organize
  .tags
    = render :partial=>"share/tag_list", :locals => {:tags=>activity.tags, :controller=>:activities}
  .description
    = sanitize(activity.description, :attributes => %w(id class style href _cke_saved_href title alt width height))
  .meta
    = t '.points', :count => activity.points
    = "|"
    = link_to (t '.like', :count => activity.fans.count), activity_circle_path(activity,activity.fan_circle)
    = "|"
    = link_to (t '.join', :count => activity.members.count), activity_circle_path(activity,activity.member_circle)
    = "|"
    = link_to (t '.blogs', :count => activity.blogs.count), activity_blogs_path(activity)
    = "|"
    = link_to (t '.pictures', :count => activity.pictures.count), activity_pictures_path(activity)
.clear

app/views/activities/_like.html.haml
%span.like
  - if can? :like, activity
    = link_to (t '.like'), like_activity_path(activity), :remote => true
  - else
    = link_to (t '.unlike'), unlike_activity_path(activity), :remote => true

app/views/activities/_navbar.html.haml
%ul.navbar.nav.nav-list
  %li.nav-header
    = t '.navi'
  %li
    %a{:href => "#{activity_circles_path(@activity)}"}
      %i.icon-user
      = t '.members'
  %li
    %a{:href => "#{activity_blogs_path(@activity)}"}
      %i.icon-file
      = t '.blog'
  %li
    %a{:href => "#{activity_albums_path(@activity)}"}
      %i.icon-picture
      = t '.picture'
      

app/views/activities/_pictures.html.haml
.pictures
  %span.label.label-info
    = t "Picture"
  .picture-warpper
    - if @activity.pictures.empty?
      .alert.alert-info
        = link_to 'x', '', :class => 'close', 'data-dismiss' => 'alert'
        = t '.empty'
    - else
      .image_carousel
        .carousel-items
          - @activity.pictures.each do |pic|
            = link_to (image_tag pic.url(:small)), "#picture-ori-#{pic.id}", :class => "gallery_pics fancybox.inline", :title => "<div class=\"pic-title\">#{link_to pic.album.title,pic.album}<br />by:#{link_to pic.user.name,pic.user}<br /></div>"+pic.remark, :"data-fancybox-group" => "gallery"
        .clear
        %a.prev{:href => '#'}
          %i.icon-arrow-left
        %a.next{:href => '#'}
          %i.icon-arrow-right
      .inline-hide
        - @activity.pictures.each do |pic|
          %div{:id=>"picture-ori-#{pic.id}"}=link_to image_tag(pic.url(:big)), pic
      .more.row
        - if @activity.pictures.count>5
          = link_to (t '.more'), activity_albums_path(@activity), :class => 'btn btn-info span3 offset2'

app/views/activities/_side.html.haml
.side.span2
  .poster
    = link_to (image_tag activity.card), activity
  .role
    = activity.role(current_user) if activity.members.include?(current_user)
  .like-join
    - unless activity.members.include?(current_user)
      = render :partial => 'activities/like', :locals => { :activity => activity }
    = render :partial => 'activities/join', :locals => { :activity => activity }
  .location
    %span= t '.location'
    %span= activity.location
  .time
    .begin
      %span= t '.begin'
      %span= l activity.start_at, :format => :short
    .end
      %span= t '.end'
      %span= l activity.end_at, :format => :short

app/views/activities/_toolbar.html.haml
%ul.toolbar.nav.nav-list
  %li.nav-header
    = t '.admin'
  %li
    %a{:href => "#{edit_activity_path(@activity)}"}
      %i.icon-pencil
      = t '.edit'
  %li
    %a{:href => "#{activity_circles_path(@activity)}"}
      %i.icon-user
      = t '.members'
  %li
    %a{:href => "#{activity_blogs_path(@activity)}"}
      %i.icon-file
      = t '.blog'
  %li
    %a{:href => "#{activity_albums_path(@activity)}"}
      %i.icon-picture
      = t '.picture'
      

app/views/activities/index.html.haml
= render :partial => 'hot'
= render :partial => 'filter'
= render :partial => 'card', :collection => @activities, :as => :activity

app/views/activities/new.html.haml
= simple_form_for @activity, :html => {:class => 'form-horizontal'} do |f|
  = f.hidden_field :group_id
  %fieldset
    %legend
      = t '.title'
    = f.input :title
    = f.input :tag_list, :input_html => {:class => "tags_input"}
    = f.input :start_at, :input_html => {:class => 'span1'}
    = f.input :end_at, :input_html => {:class => 'span1'}
    = f.input :location, :class => 'span4'
    = f.input :public
    = f.input :poster
    = f.input :description, :input_html => {:class => 'span4', :rows => 10}
    .form-actions
      %button.btn.btn-primary{:type => 'submit'}
        = t '.new'
      %a.btn{:href => group_path(@group)}
        = t '.cancel'

app/views/activities/show.html.haml
= render :partial => 'board', :object => @activity, :as => :activity
= render :partial => 'blogs'
= render :partial => 'pictures'
= render :partial => 'comments'

app/views/activities/tag_cloud.html.haml
- tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
  = link_to tag.name, { :action => :tag, :tag_name => tag.name}, :class => css_class

app/views/activities/wall.html.haml
= render :partial => 'filter'
.content.wall
  .hot
    .title= t '.wall'
    - @activities.each do |activity|
      = link_to (image_tag activity.poster.url(:card)), activity